version: '3'
services:
  cursowebservice-api:
    build:
      context: ./
      dockerfile: ./dockerfile
    image: cursowebservice/api
    ports:
    - "8080:8080"
    - "5005:5005"
    environment: 
      - PROFILE=dev
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xms128m -XX:MaxMetaspaceSize=128m
